[general]
  import = [
  "~/.config/alacritty/kanagawa_dragon.toml"
  ]
  live_config_reload = true
[font]
  normal = { family = "FiraCode Nerd Font", style = "Regular" }
  size = 11.0
[window]
  opacity = 0.93
